name: Run Ansible Playbook
on: [push]
jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: roles/meican/tests/test.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: --verbose

      - name: Print home directory tree
        run: 'tree /home/meican/'

      - name: List all users
        run: 'cut -d: -f1 /etc/passwd'


